	{{ HTML::script('/assets/dist/support/js1/pace.min.js') }}
	{{ HTML::script('/assets/dist/support/js1/jquery.min.js') }}
	{{ HTML::script('/assets/dist/support/js1/jquery.cookie.js') }}
	{{ HTML::script('/assets/dist/support/js1/bootstrap.min.js') }}
	{{ HTML::script('/assets/dist/support/js1/newsTicker.js') }}
	{{ HTML::script('/assets/dist/support/js1/jquery.mCustomScrollbar.concat.min.js') }}
	{{ HTML::script('/assets/dist/support/js1/animo.min.js') }}
	{{ HTML::script('/assets/dist/support/js1/bootstrap-progressbar.min.js') }}
	{{ HTML::script('/assets/dist/support/js1/jquery.easypiechart.min.js') }}
	{{ HTML::script('/assets/dist/support/js1/jquery.sparkline.min.js') }}
	{{ HTML::script('/assets/dist/support/js1/summernote.min.js') }}
	{{ HTML::script('/assets/dist/support/js1/app.js') }}
	{{ HTML::script('/assets/dist/support/js1/demo.js') }}
	{{ HTML::script('/assets/dist/support/js1/mailbox.js') }}
    {{ HTML::script('/assets/dist/support/js1/moment.js') }}    
    {{ HTML::script('/assets/dist/support/js1/livestamp.min.js') }}	
<!-- 	{{ HTML::script('/assets/dist/support/js1/') }}
	{{ HTML::script('/assets/dist/support/js1/') }}
	{{ HTML::script('/assets/dist/support/js1/') }}
	{{ HTML::script('/assets/dist/support/js1/') }}
	{{ HTML::script('/assets/dist/support/js1/') }}
	{{ HTML::script('/assets/dist/support/js1/') }} -->
    {{ HTML::script('/assets/dist/support/js/support.js') }}
    {{ HTML::script('/assets/dist/support/js/jquery.dataTables.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.bootstrap.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.bootstrap.min.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.bootstrap4.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.bootstrap4.min.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.foundation.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.foundation.min.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.jqueryui.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.jqueryui.min.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.material.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.material.min.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.semanticui.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.semanticui.min.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.uikit.js') }}    
    {{ HTML::script('/assets/dist/support/js/dataTables.uikit.min.js') }}     
    {{ HTML::script('/assets/dist/support/js/jquery.dataTables.min.js') }}	
